openapi: 3.0.0
info:
  title: Swagger OpenAPI 3 Multipart/Form-Data Example
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username (must not contain whitespace)
                password:
                  type: string
                  format: password
                  description: Password (6-18 characters)
                email:
                  type: string
                  format: email
                  description: Email address
                fullName:
                  type: string
                  description: Full name
                phone:
                  type: string
                  description: Phone number
                avatar:
                  type: string
                  format: binary
                  description: Avatar file (image/png, image/jpeg, etc.)
                gender:
                  type: string
                  enum: [ MALE, FEMALE, OTHER ]
                  description: Gender
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Bad request - validation errors or missing fields
