package com.fpt.cursus.controller;

import com.fpt.cursus.service.AccountService;
import com.fpt.cursus.service.CourseService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

@RestController
@CrossOrigin("*")
@SecurityRequirement(name = "api")
@Tag(name = "User Controller")
public class UserController {

    private final AccountService accountService;
    private final CourseService courseService;

    @Autowired
    public UserController(AccountService accountService,
                          CourseService courseService) {
        this.accountService = accountService;
        this.courseService = courseService;
    }

    @Operation(summary = "Send verifying instructor to admin",
            description = "Role default is STUDENT, need to call this Api to be INSTRUCTOR\n"
                    + "cvLink must to be generated by File Controller")
    @PostMapping("/send-cv")
    public ResponseEntity<Object> sendCv(@RequestParam("file") MultipartFile file) {
        return ResponseEntity.status(HttpStatus.OK).body(accountService.sendCv(file));
    }

    @Operation(summary = "view instructor by name", description = "input a partial name of instructor")
    @GetMapping("/view-instructor")
    public ResponseEntity<Object> getInstructor(@RequestParam String name) {
        return ResponseEntity.status(HttpStatus.OK).body(accountService.getInstructorByName(name));
    }

    @PostMapping("/wishlist/add")
    public ResponseEntity<Object> addToWishList(@RequestParam List<Long> id) {
        return ResponseEntity.status(HttpStatus.OK)
                .body(courseService.addToWishList(id));
    }

    @DeleteMapping("/wishlist/remove")
    public ResponseEntity<Object> removeFromWishList(@RequestParam Long id) {
        return ResponseEntity.status(HttpStatus.OK)
                .body(courseService.removeFromWishList(id));
    }

    @GetMapping("/wishlist/view")
    public ResponseEntity<Object> viewWishList(@RequestParam(required = false) String sortBy,
                                               @RequestParam(defaultValue = "1", required = false) int offset,
                                               @RequestParam(defaultValue = "10", required = false) int pageSize) {
        return ResponseEntity.status(HttpStatus.OK)
                .body(courseService.getWishListCourses(offset, pageSize, sortBy));
    }

    @GetMapping("/enrolled-course/view-all-general")
    public ResponseEntity<Object> viewEnrolledCourses(@RequestParam(required = false) String sortBy,
                                                      @RequestParam(defaultValue = "1", required = false) int offset,
                                                      @RequestParam(defaultValue = "10", required = false) int pageSize) {

        return ResponseEntity.status(HttpStatus.OK)
                .body(courseService.getGeneralEnrolledCourses(sortBy, offset, pageSize));
    }

    @GetMapping("/enrolled-course/view-all-detail")
    public ResponseEntity<Object> viewDetailEnrolledCourses(@RequestParam(required = false) String sortBy,
                                                            @RequestParam(defaultValue = "1", required = false) int offset,
                                                            @RequestParam(defaultValue = "10", required = false) int pageSize) {
        return ResponseEntity.status(HttpStatus.OK)
                .body(courseService.getDetailEnrolledCourses(sortBy, offset, pageSize));
    }

    @Operation(summary = "View course created by current user",
            description = "view course which created by current user, for admin and instructor")
    @GetMapping("/view-my-course")
    @PreAuthorize("hasAuthority('ADMIN') || hasAuthority('INSTRUCTOR') ")
    public ResponseEntity<Object> viewMyCourse(@RequestParam(required = false) String sortBy,
                                               @RequestParam(defaultValue = "1", required = false) int offset,
                                               @RequestParam(defaultValue = "10", required = false) int pageSize) {

        return ResponseEntity.status(HttpStatus.OK)
                .body(courseService.getCourseByCreatedBy(offset, pageSize, sortBy));
    }

}
