package com.fpt.cursus.enums.type;

public enum Category {
    ALL,
    PHYSICS,
    CHEMISTRY,
    COMPUTER_SCIENCE,
    INFORMATION_TECHNOLOGY,
    ENGINEERING,
    FINANCE,
    MARKETING,
    HUMAN_RESOURCES,
    LITERATURE,
    HISTORY,
    PHILOSOPHY,
    VISUAL_ARTS,
    MUSIC,
    PSYCHOLOGY,
    SOCIOLOGY,
    ANTHROPOLOGY,
    ECONOMICS,
    NURSING,
    PUBLIC_HEALTH,
    NUTRITION,
    LAW,
    LANGUAGE,
    GRAPHIC_DESIGN,
    JOURNALISM
}

